###########################################
# 基础域名
#site.url: "http://www.yike.com"
###########################################
# 文件存储根目录
filestorage.root: /data1/node1/hejia

###########################################
# redis服务
redis.host: 127.0.0.1
redis.port: 6379

###########################################
# mybatis 数据库配置
mybatis.environment.id: prod
JDBC.driver: com.mysql.jdbc.Driver
JDBC.url: "jdbc:mysql://127.0.0.1:3306/hejia_prod?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8"
JDBC.username: sudao
JDBC.password: sudao
JDBC.autoCommit: false
c3p0.maxIdleTime: 60
c3p0.maxPoolSize: 200
c3p0.minPoolSize: 50
c3p0.initialPoolSize: 50

###########################################
# elasticsearch搜索服务配置
elasticsearch.cluster.nodes: "127.0.0.1:9300"
elasticsearch.index.name: hejia_prod

###########################################
# 是否开启短信：true | false
sms.enabled: true
